# Generated by Django 3.2 on 2023-05-21 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='code',
            name='code_user_unique',
        ),
        migrations.RenameField(
            model_name='code',
            old_name='code',
            new_name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='code',
            name='user',
        ),
        migrations.AddField(
            model_name='code',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='username_code', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='code',
            constraint=models.UniqueConstraint(fields=('confirmation_code', 'username'), name='code_user_unique'),
        ),
    ]
