# Generated by Django 3.2 on 2023-05-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230521_0333'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='code',
            name='code_user_unique',
        ),
        migrations.RenameField(
            model_name='code',
            old_name='username',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='code',
            constraint=models.UniqueConstraint(fields=('confirmation_code', 'user'), name='code_user_unique'),
        ),
    ]
