# Generated by Django 3.2 on 2023-05-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230521_0346'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='code',
            name='code_user_unique',
        ),
        migrations.RemoveField(
            model_name='code',
            name='user',
        ),
        migrations.AddField(
            model_name='code',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddConstraint(
            model_name='code',
            constraint=models.UniqueConstraint(fields=('confirmation_code', 'username'), name='code_user_unique'),
        ),
    ]
